import {
  CREATE_ACCESS_POLICIES,
  CREATE_ACCESS_POLICIES_INDEXES,
  CREATE_AUDIT_LOG,
  CREATE_AUDIT_LOG_INDEXES,
  CREATE_SECRETS,
  CREATE_SECRETS_INDEXES,
  CREATE_VAULT_META,
} from "../schema.js";

export const migration001 = {
  version: 1,
  up: [
    CREATE_VAULT_META,
    CREATE_SECRETS,
    CREATE_SECRETS_INDEXES,
    CREATE_ACCESS_POLICIES,
    CREATE_ACCESS_POLICIES_INDEXES,
    CREATE_AUDIT_LOG,
    CREATE_AUDIT_LOG_INDEXES,
  ].join("\n"),
};
